language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.5.3 WP_MULTISITE=0
  - WP_VERSION=4.5.3 WP_MULTISITE=1
  - WP_VERSION=4.4.4 WP_MULTISITE=0
  - WP_VERSION=4.4.4 WP_MULTISITE=1

cache:
  bundler: true
  directories:
  - node_modules # NPM packages
  - vendor # Composer packages

# Clones WordPress and configures our testing environment.
before_script:
  # Setup Coveralls
  - phpenv local 5.6
  - composer install --no-interaction
  - phpenv local --unset

  - npm install

  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - grunt checktextdomain
  - vendor/bin/phpmd includes text codesize,naming,unusedcode
  - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml includes
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter